name: "Chris Kanich"
description: "Assistant Professor Chris Kanich's personal web page."
author: "Chris Kanich"
googlescholar: "https://scholar.google.com/citations?user=Zy1b3UAAAAAJ&hl=en"
baseurl: "/~ckanich"

exclude: ["Makefile","README.md"]

viewsource: "https://github.com/kaytwo/website"

gems: ["jekyll/scholar"]

sections: [home, publications]

scholar:
  style: _includes/ieee.csl

  sort_by: year,month
  order: descending
  
  bibliography: publications.bib
  source: _includes/
  repository: papers
  bibliography_template: "{{reference}} {% if link %} <a href='{{link}}'>PDF</a> {% endif %}"

