name: "Chris Kanich"
description: "Assistant Professor Chris Kanich's personal web page."
author: "Chris Kanich"

baseurl: "/~ckanich"

exclude: ["README.md"]

gems: ["jekyll/scholar"]

sections: [home, publications]

scholar:
  style: _includes/ieee.csl

  bibliography: publications.bib
  source: _includes/
  repository: papers
  bibliography_template: "{{reference}} {% if link %} <a href='{{link}}'>PDF</a> {% endif %}"

